Week4
Finelai/loft-taxi pull request #4
Opened 2021-02-18 16:37 UTC by Finelai

1. Подключена redux-saga
2. Middleware переписаны на sagas
3. Добавлены новые саги и запросы к апи сервера
4. Добавлена форма с данными карты пользователя и реализовано получение и отправка их
5. Добавлен фукнционал регистрации
6. На карту добавлена форма с адресама, получение адресов при логине пользователя
7. Реализовано получение координат для построения маршрута

2021-02-19 16:05 UTC, R-Oscar requested changes

2021-02-19 16:05 UTC, R-Oscar commented on src/Components/Map.jsx
> +import { receiveRoute, getAdressList } from "modules/map";
Переименуй в getAddressList

2021-02-19 16:05 UTC, R-Oscar commented on src/Components/Map.jsx
> +    adressList: PropTypes.array,
И тут тоже `addressList`

2021-02-19 16:05 UTC, R-Oscar commented on src/Components/Map.jsx
> +              <option value={this.props.adressList[1]}></option>
Тут надо делать `addressList.map`

2021-02-19 16:05 UTC, R-Oscar commented on src/Components/Profile.jsx
> +    userCardCVC: PropTypes.number
Я бы последние 4 поля объединил в объект, т.е.
```
card: {
  number,
  name,
  expiryDate,
  CVC
}
```

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/map/actions.js
> +export const saveAdressList = createAction("MAP_SAVE_ADRESS_LIST");
Тоже лучше address поправить

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/map/reducer.js
> +        adressList: action.payload
Тут у тебя затирается предыдущий стейт. Чтобы этого не происходило, нужно делать так:

```
return {
  ...state,
  addressList: action.payload
}
```

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/map/reducer.js
> +        route: action.payload
Тоже самое со стейтом

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/map/sagas.js
> +  if (data.cardNumber != "") {
Какое-то странное условие, при чем тут номер карты и список адресов?

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/map/sagas.js
> +    toast("Маршрут построен");
Наверное правильнее этот тост показывать когда выполнится функция drawRoute а не когда выполнится запрос в саге

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/user/reducer.js
> +  cardNumber: null,
Тут тоже лучше объединить все, что связано с картой, в объект

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/user/sagas.js
> +    toast("Вы успешно зарегистрировались и вошли в систему");
Тоже лучше вынести на уровень компонента

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/user/sagas.js
> +    yield put(getCard(data.token));
Зачем всё сразу делать? Пусть сага логина только логином и занимается. Сага получения данных профиля должна вызываться тогда когда пользователь переходит на страницу профиля, зачем заранее эти данные запрашивать? Получение списка адресов я бы тоже триггерил из компонента карты в `componentDidMount`

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/user/sagas.js
> +  if (data.cardNumber != "") {
Тут надо сделать строгое неравенство `!==`

2021-02-19 16:05 UTC, R-Oscar commented on src/modules/user/selectors.js
> +export const getUserCardName = (state) => (state.userReducer.cardName);
Думаю если ты сделаешь объект card, тут можно будет обойтись одним селектором

2021-02-20 11:55 UTC, R-Oscar requested changes
1

2021-02-20 14:34 UTC, Finelai commented on src/modules/user/sagas.js
> +    yield put(getCard(data.token));
Делалось из соображений экономии времени пользователя. Чтобы он не ждал сетевых запросов при заходе на страницу, а они выполнялись фоном.

2021-02-20 14:38 UTC, R-Oscar commented on src/modules/user/sagas.js
> +    yield put(getCard(data.token));
Но при этом у тебя +1 запрос будет на главной и это замедлит её работу, лучше так не делать

2021-02-20 14:45 UTC, Finelai commented on src/modules/user/sagas.js
> +    yield put(getCard(data.token));
Понял, а асинхронность в данном случае ничего не значит?

2021-02-23 07:33 UTC, R-Oscar approved these changes

2021-02-23 07:33 UTC, R-Oscar commented on src/Components/Map.jsx
> +                <option key={i}>{item}</option>
Тут можно `key={item}` поставить, т.к. название адреса уникально у нас

2021-02-23 07:33 UTC, R-Oscar commented on src/modules/map/reducer.js
> +      return {
Тут можно просто `return { ... state }` сделать

2021-02-23 07:37 UTC, R-Oscar commented on src/Components/Map.jsx
> +                <option key={i}>{item}</option>
И тут ещё надо реализовать фильтрацию, чтобы не показывать выбранный в другом селекте роут (через `.filter`)

2021-02-23 17:28 UTC, merged