Week5
Finelai/loft-taxi pull request #5
Opened 2021-03-05 11:02 UTC by Finelai

2021-03-10 10:26 UTC, R-Oscar requested changes

2021-03-10 10:26 UTC, R-Oscar commented on src/App.jsx
> +              <Redirect to="/login" />
Этот редирект тут точно нужен? У тебя же `PrivateRoute` реализовывает редирект на страницу логина

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Header/Header.jsx
> +          <Logo></Logo>
Тут лучше сократить до `<Logo />`

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Header/Header.jsx
> +      <AppBar position="static" color="#ffffff">
Попробуй задать цвет через CSS modules

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Login/Login.jsx
> +  const { register, handleSubmit } = useForm();
Тут желательно добавить валидацию
https://react-hook-form.com/get-started#Handleerrors

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Login/Login.jsx
> +        <Redirect to="/profile" />
Это условие можно вынести наверх, тем самым разгрузив рендер

```
if (props.isLoggedIn) {
  return <Redirect to="/profile" />
}

return (
  <Grid ...>
    ...
  </Grid>
);
```

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Map/Map.jsx
> +    console.log(this.props.userCard);
Консоль логи надо выпилить

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Map/Map.jsx
> +        {this.props.userCard.number && this.props.addressList && this.props.addressList.length > 0 ? (
Эту запись можно сократить через optional chaining:

`this.props.userCard.number && this.props.addressList?.length > 0`

И лучше вынести в переменную, например `showMapForm`

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Map/MapForm.jsx
> +          <option key={i}>{item}</option>
Индексы в качестве ключей [не очень хорошая практика](https://ru.reactjs.org/docs/lists-and-keys.html#keys)
Тут можно юзать item в качестве ключа

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Profile/Profile.jsx
> +    console.log(data);
Консоль надо убрать

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Profile/Profile.jsx
> +        <input type="text" name="card" placeholder="Номер карты" value={(props.userCard && props.userCard.number) ? props.userCard.number : undefined } ref={register} />
Тут тоже можно написать просто
`value={props.userCard?.number}`

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Profile/Profile.jsx
> +      <button style={{ float: "right" }} onClick={handleLogoutBtn}>Выйти из профиля</button>
Может как-нибудь на флексах сделать?) Непривычно видеть float в современной разметке

2021-03-10 10:26 UTC, R-Oscar commented on src/components/Reg/Reg.jsx
> +  const { register, handleSubmit } = useForm();
Тут тоже не помешала бы валидация

2021-03-10 10:26 UTC, R-Oscar commented on src/redux/modules/map/sagas.js
> +  console.log("get address list saga");
Консоль

2021-03-10 10:26 UTC, R-Oscar commented on src/utils/api.js
> +  // return fetch(
Тут надо вернуть логику

2021-03-10 10:41 UTC, Finelai commented on src/App.jsx
> +              <Redirect to="/login" />
Это route по умолчанию. PrivateRoute запрещает заходить на определенные страницы

2021-03-16 17:01 UTC, Finelai commented on src/components/Header/Header.jsx
> +      <AppBar position="static" color="#ffffff">
Получилось. Надо было обернуть **App** в **StylesProvider** с атрибутом **injectFirst** чтобы стили из модулей стали приоритетней.

2021-05-17 12:12 UTC, merged